### ISSUE TITLE
EasyUpload link is expired

### ISSUE THREAD

**Issue by ItsGoldeneyes** [GistNoesis/BrickRegistration#2]
Title, I'd love to use the dataset for my own projects. Otherwise, I'll create my own and share it here from https://printablebricks.com/

**Comment by unrealwill** [comment]
Here is the file, served from one of my servers (won't be there forever, but probably longer than the easy upload links).
[legoSTLandURDF.tar.gz](http://orchid.gistnoesis.net/legoSTLandURDF.tar.gz)
It's an old file, and there may have been newer pieces since. 
I'm not currently actively maintaining this project, so expect some small bugs as code that depends on external data and services tend to rust quite fast.
